apiVersion: v1 # admin
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    mongo-root-username: ZGJyb290 # echo -n 'dbroot' | base64
    mongo-root-password: ZGJwYXNz # echo -n 'dbpass' | base64